allprojects {
    repositories {
        google()
        mavenCentral()
    }
    
    plugins.withId("com.android.base") {
        android {
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }
        }
    }

    plugins.withId("com.android.application") {
        android {
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }
        }
    }

    plugins.withId("com.android.library") {
        android {
            if (namespace == null) {
                def manifestFile = file("src/main/AndroidManifest.xml")
                if (manifestFile.exists()) {
                    def manifest = new XmlSlurper(false, false).parse(manifestFile)
                    namespace = manifest.@package.text()
                }
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }
        }
    }

    plugins.withId("org.jetbrains.kotlin.android") {
        kotlin {
            jvmToolchain(17)
        }
    }
    
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            jvmTarget = "17"
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
