org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36
android.nonTransitiveRClass=false
android.kotlinOptions.jvmTarget=17
kotlin.jvm.target.validation.mode=warning
