// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cz-6jFO252pZ75HgPTm_sstMvtli1uk',
    appId: '1:360848321721:web:abcdef123456',
    messagingSenderId: '360848321721',
    projectId: 'finwise-c934d',
    authDomain: 'finwise-c934d.firebaseapp.com',
    storageBucket: 'finwise-c934d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0cz-6jFO252pZ75HgPTm_sstMvtli1uk',
    appId: '1:360848321721:android:cbf1ab5bef8cf4586b7f68',
    messagingSenderId: '360848321721',
    projectId: 'finwise-c934d',
    storageBucket: 'finwise-c934d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0cz-6jFO252pZ75HgPTm_sstMvtli1uk',
    appId: '1:360848321721:ios:abcdef123456',
    messagingSenderId: '360848321721',
    projectId: 'finwise-c934d',
    storageBucket: 'finwise-c934d.firebasestorage.app',
    iosClientId: '360848321721-abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.budget.tracker-app',
  );
}
